# These settings are synced to GitHub by https://probot.github.io/apps/settings/
_extends: .github

repository:
  description: "🛠️ Universal Tool for DevOps and Cloud Automation (works with terraform, helm, kubectl, aws and etc) "
  topics: "ivank, scripts, devops, k8s, automation"
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: false
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: false
